on: [push]

jobs:
  schema_validation_job:
    runs-on: ubuntu-latest
    name: Schame validation
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: test a single file
        id: single
        uses: eXpire163/yamale-docker-action@main
        with:
          schema-file: "schema.yml"
          test-file: "action.yml"
          strict: "nonstrict"
      - name: or test a folder
        id: folder
        uses: eXpire163/yamale-docker-action@main
        with:
          schema-file: "schema.yml"
          test-file: "testfiles"
          strict: "strict"

      - name: Get the output time
        run: echo "The time was ${{ steps.single.outputs.time }}"
